### ISSUE TITLE
!sgif errors sometimes

### ISSUE THREAD

**Issue by LuCa-0** [MhankBarBar/whatsapp-bot#93]
Hi!
Awesome project! I really love it.
Sadly sometimes when i try to convert a video to animated sticker i get the following error:
```
~> [EXEC] 29/10 20:54:48 !sgif from Luca
(node:33468) UnhandledPromiseRejectionWarning: Error: Evaluation failed: t
    at ExecutionContext._evaluateInternal (/Users/luca/Downloads/whatsapp-bot-master/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async ExecutionContext.evaluate (/Users/luca/Downloads/whatsapp-bot-master/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:106:16)
(node:33468) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:33468) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Any idea on how to solve this?

**Comment by LuCa-0** [comment]
I did some tests and seems like it happens when the converted .gif is more than 3Mb. Maybe the base64 conversion has issues? Thank you so much.

**Comment by LuCa-0** [comment]
Why did you close this? It's still an issue...

**Comment by 416145** [comment]
Hi LuCa-0!

I had the same issue yesterday. With some debugging I found out it only happens when you try to convert a large video. Small videos to animated stickers are no problem. Is this the same for you? I think the issue is that the base64 conversion only can handle files op to a certain file size.

Anyway, I fixed it by adding some try/catches. So when the program can't convert it to a sticker it tries it again with less FPS. The code isn't very clean, but at least it works ;)
